# Generated by Django 4.0.4 on 2022-07-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_catalog_videolink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='catalog',
        ),
        migrations.DeleteModel(
            name='customersupportmodel',
        ),
        migrations.DeleteModel(
            name='VideoLink',
        ),
    ]
