# Generated by Django 4.0.4 on 2022-07-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_catalog_delete_customersupportmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.FileField(blank=True, upload_to='sovenir_cat', verbose_name='provide a catalogue here...')),
            ],
        ),
    ]
