# Generated by Django 4.0.4 on 2022-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='catalogue_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
